In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns

In [2]:
data = pd.read_csv('C:\jupyter\dataset_tugas\covid_19_india.csv')

In [3]:
data.head(10)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
5,6,2020-02-04,6:00 PM,Kerala,3,0,0,0,3
6,7,2020-02-05,6:00 PM,Kerala,3,0,0,0,3
7,8,2020-02-06,6:00 PM,Kerala,3,0,0,0,3
8,9,2020-02-07,6:00 PM,Kerala,3,0,0,0,3
9,10,2020-02-08,6:00 PM,Kerala,3,0,0,0,3

In [4]:
data.shape

(18110, 9)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
Sno                         18110 non-null int64
Date                        18110 non-null object
Time                        18110 non-null object
State/UnionTerritory        18110 non-null object
ConfirmedIndianNational     18110 non-null object
ConfirmedForeignNational    18110 non-null object
Cured                       18110 non-null int64
Deaths                      18110 non-null int64
Confirmed                   18110 non-null int64
dtypes: int64(4), object(5)
memory usage: 1.2+ MB

In [6]:
data.describe()

                Sno         Cured         Deaths     Confirmed
count  18110.000000  1.811000e+04   18110.000000  1.811000e+04
mean    9055.500000  2.786375e+05    4052.402264  3.010314e+05
std     5228.051023  6.148909e+05   10919.076411  6.561489e+05
min        1.000000  0.000000e+00       0.000000  0.000000e+00
25%     4528.250000  3.360250e+03      32.000000  4.376750e+03
50%     9055.500000  3.336400e+04     588.000000  3.977350e+04
75%    13582.750000  2.788698e+05    3643.750000  3.001498e+05
max    18110.000000  6.159676e+06  134201.000000  6.363442e+06

In [7]:
data.isnull().sum()

Sno                         0
Date                        0
Time                        0
State/UnionTerritory        0
ConfirmedIndianNational     0
ConfirmedForeignNational    0
Cured                       0
Deaths                      0
Confirmed                   0
dtype: int64

In [17]:
labels = ['sembuh','mati']
size = data ['kasus'].value_counts()
explode = [0,0.2]
plt.rcParams['figure.figsize']=(7,7)
plt.pie(size, explode = explode, labels = labels, shadow = False, autopct = '%.F%%')
plt.title ('kasus', fontsize = 20)
plt.axis ('off')
plt.legend()
plt.show()

KeyError: 'kasus'